version: '3.8'
volumes:
  postgres_data:
  static_volume:
  media_volume:

services:
  db:
    image: postgres:13.1
    container_name: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    image: fr33vvay/foodgram:latest
    container_name: django
    restart: always
    volumes:
      - static_volume:/code/staticfiles
      - media_volume:/code/media
    depends_on:
      - db
    env_file:
      - ./.env
  nginx:
    image: nginx:1.19.4
    container_name: webserver
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/code/staticfiles
      - media_volume:/code/media
    ports:
      - 80:80
    depends_on:
      - web