# Generated by Django 3.1.4 on 2020-12-05 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20201203_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amount',
            name='quantity',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
