# Generated by Django 3.1.4 on 2020-12-20 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_auto_20201205_2323'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscribe',
        ),
    ]
