# Generated by Django 3.1.4 on 2020-12-31 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0017_remove_tag_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
    ]
